### ISSUE TITLE
[tracker] docs: Documentation tracking issue

### ISSUE THREAD

**Issue by ghost** [managarm/managarm#174]
Over time, as the Managarm project grows even further we have to invest in documenting the whole project to make it easier for new users and contributors to use and develop for Managarm.

### Introduction
- [ ] Quick introduction
    - What is Managarm
    - What makes Managarm different from other OSes
    - Goals of Managarm

### Getting started
- [ ] Detailed getting started guide
    - How to try out Managarm
    - How to setup the development environment for working on the OS
    - How to setup a developmenet environment for porting applications to the OS

- [ ] Contribution Guide and Guidelines

### Structure
- [ ] xbstrap

- [ ] The structure of the Managarm kernel and its base components
    - Managarm
    - Bragi
    - mbus
    - frigg
    - libasync
    - hel/helix
    - eir
    - thor
    - posix subsystem
    - different base servers

### Developing for Managarm
- [ ] Add new hardware support / drivers to managarm

### Enforcing Documentation
We should also enforce documentation in some components when they get added or important stuff gets changed. But thats something @avdgrinten should decide on how we solve that. I suggest as talked before on the Discord that it has to be a part of the pullrequest, which also gets checked by somebody of the docs team before merge for quality-assurance.

### Contributing to the docs and suggestions
Everybody is welcome to contribute to the documentation. If there are other topics that you think should be covered, feel free to suggest them here in the comments.

**Comment by avdgrinten** [comment]
Maybe @Dennisbonke can take care of this issue.

**Comment by Dennisbonke** [comment]
I can be assigned to this issue yes

**Comment by avdgrinten** [comment]
This issue is no longer useful; additional issues for documentation can be tracked via projects.
