### ISSUE TITLE
General Network issue tracker

### ISSUE THREAD

**Issue by ElectrodeYT** [managarm/managarm#541]
At the moment, we have the following issues with netserver:

- [ ] No loopback device (solved poorly locally)
- [ ] Single-threaded (co-routines make multiple NICs possible, but not very well: if one had two nics, and one got into a non-coroutine busy loop, its possible the other one might hang)
- [ ] All network drivers are in the same service, which is also not ideal
- [ ] No DHCP

Ideally, netserver would not be directly interfacing the NICs anyway; each NIC would have its own server (like graphics devices currently do) which would talk to netserver.

**Comment by qookei** [comment]
The fact it's single-threaded does not make multiple NICs work poorly, poor drivers do. A driver should not busy wait without cooperatively sleeping or use non-cooperative sleeps (e.g. instead of `sleep` one should use `co_await helix::sleepFor`).

**Comment by ElectrodeYT** [comment]
> 

I'm aware, but the fact that its possible in the first place is sub optimal. What could be more likely is if one interface is being blasted, it could cause other interfaces to not get time to receive packets, which on some cards could cause packets to be dropped, which is also not very good. Best to avoid this situation in the first place.

**Comment by ArsenArsen** [comment]
yes, it can be avoided by not sleeping in drivers.  multithreading the netserver will be useful down the line, but it doesn't fix this issue

**Comment by avdgrinten** [comment]
Multi-threading can of course improve performance. In the long term, it'd be nice to make the server multi-threaded. However, I don't think that it impacts multi-NIC operation (at least not for now). Drivers should not block / busy loop anyway.
